# Generated by Django 3.2.3 on 2021-09-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210926_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='dueDate',
            new_name='due',
        ),
    ]
